name: Build & Publish to sahilmalik5547.github.io

on:
  push:
    branches: [ "main" ]  # adjust if you deploy from another branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present

      - name: Deploy dist/browser to public repo
        env:
          PUBLIC_REPO: https://x-access-token:${{ secrets.PUBLIC_PAT }}@github.com/sahilmalik5547/sahilmalik5547.github.io.git
        run: |
          # ensure build output exists
          if [ ! -d dist/browser ]; then
            echo "Build output dist/browser not found" >&2
            exit 1
          fi

          # Prepare git repo from dist/browser
          cd dist/browser
          git init
          git checkout -b main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy portfolio from private repo @$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git remote add origin "$PUBLIC_REPO"
          git push --force origin main
